"""cria tabela users

Revision ID: 4f7566187c78
Revises: 20260923_ouvidoria_star_schema
Create Date: 2026-10-07 13:29:08.065392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f7566187c78'
down_revision: Union[str, Sequence[str], None] = '20260923_ouvidoria_star_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('idx_fato_upload_id'), table_name='fato_manifestacoes')
    op.create_index(op.f('ix_fato_manifestacoes_upload_id'), 'fato_manifestacoes', ['upload_id'], unique=False)
    op.drop_index(op.f('idx_uploads_planilhas_competencia'), table_name='uploads_planilhas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_uploads_planilhas_competencia'), 'uploads_planilhas', ['competencia_ano_mes'], unique=False)
    op.drop_index(op.f('ix_fato_manifestacoes_upload_id'), table_name='fato_manifestacoes')
    op.create_index(op.f('idx_fato_upload_id'), 'fato_manifestacoes', ['upload_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('department', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###
